### ISSUE TITLE
jss-cli not registered in npmjs.com?

### ISSUE THREAD

**Issue by hh9527** [jsstyles/jss-cli#2]
```
$ npm install jss-cli --save-dev
...
npm ERR! 404 404 Not Found: jss-cli
...
```

And I searched in www.npmjs.com, found nothing.

**Comment by joshgillies** [comment]
Yup, currently the CLI is still bundled with the `jss` package. So `npm i jss -D` will get you the CLI and API.

**Comment by kof** [comment]
oh no I just forgot to publish it, its not in jss any more

**Comment by kof** [comment]
done

**Comment by kof** [comment]
both new jss version without cli and published cli
